### ISSUE TITLE
No module named Crypto.Hash

### ISSUE THREAD

**Issue by CashCode** [xran-deex/PyCoin#7]
Hey!
Having an issue with crypto library, I tried every version of it, but it still gives error: 
```C:\Users\ext>python3 C:\Users\ext\Desktop\pc\lib\gui.py
Traceback (most recent call last):
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 4, in <module>
    from MiningManager.miningmanager import Miner
  File "C:\Users\ext\Desktop\pc\lib\MiningManager\miningmanager.py", line 5, in
<module>
    from BlockManager.block import Block
  File "C:\Users\ext\Desktop\pc\lib\BlockManager\block.py", line 2, in <module>
    import db, utils
  File "C:\Users\ext\Desktop\pc\lib\db.py", line 2, in <module>
    from TransactionManager.transaction import Transaction
  File "C:\Users\ext\Desktop\pc\lib\TransactionManager\transaction.py", line 1,
in <module>
    from Crypto.Hash import SHA256
ImportError: No module named 'Crypto.Hash'

Is there a way to fix it? Thanks.

**Comment by xran-deex** [comment]
What version of Python are you using? 
`python --version`
What version of the pycrypto library do you have installed? 
`python -c 'import Crypto; print(Crypto.__version__)'`

**Comment by CashCode** [comment]
Python 3.5.2
AttributeError: module 'Crypto' has no attribute '__version__'

**Comment by xran-deex** [comment]
So, it appears that you are using Windows. I don't have a Window machine to test this on. I did some research, and it appears that the PyCrypto library is dead. There seem to be 2 options. 1. use `pycryptodome` instead. 2. Migrate the project to the `cryptography` module. The easiest thing right now would be for you to try the `pycryptodome` installation.

**Comment by CashCode** [comment]
Same...
```
C:\Users\ext>pip install pycryptodome
Collecting pycryptodome
  Downloading pycryptodome-3.4.3-cp35-cp35m-win32.whl (7.5MB)
    100% |################################| 7.5MB 59kB/s
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.4.3

C:\Users\ext>python3 C:\Users\ext\Desktop\pc\lib\gui.py
Traceback (most recent call last):
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 4, in <module>
    from MiningManager.miningmanager import Miner
  File "C:\Users\ext\Desktop\pc\lib\MiningManager\miningmanager.py", line 5, in
<module>
    from BlockManager.block import Block
  File "C:\Users\ext\Desktop\pc\lib\BlockManager\block.py", line 2, in <module>
    import db, utils
  File "C:\Users\ext\Desktop\pc\lib\db.py", line 2, in <module>
    from TransactionManager.transaction import Transaction
  File "C:\Users\ext\Desktop\pc\lib\TransactionManager\transaction.py", line 1,
in <module>
    from Crypto.Hash import SHA256
ImportError: No module named 'Crypto'

```

**Comment by xran-deex** [comment]
Check out the pycryptodome doc site. There are installation instructions specific to Windows. Looks like you can use a precompiled version:
https://pycryptodome.readthedocs.io/en/latest/src/installation.html#windows-pre-compiled
or build it from source:
https://pycryptodome.readthedocs.io/en/latest/src/installation.html#windows-from-sources-python-3-5-and-newer

Make sure the install succeeded by running `python -m Cryptodome.SelfTest`

**Comment by CashCode** [comment]
It was a registry problem in windows **C**rypto and **c**rypto (I've fixed before).
After installing pycryptodome, it seems to work, still get some errors, but I think I can solve it by myself.
Thanks a lot!

**Comment by CashCode** [comment]
Server works, client gui.py:
```
C:\Users\ext>python3 C:\Users\ext\Desktop\pc\lib\gui.py
Traceback (most recent call last):
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 201, in <module>
    main()
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 195, in main
    app = PyCoin(root)
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 33, in __init__
    self.initApp()
  File "C:\Users\ext\Desktop\pc\lib\gui.py", line 49, in initApp
    c = CoinBase(owner=KeyStore.getPrivateKey(), amt=100)
  File "C:\Users\ext\Desktop\pc\lib\TransactionManager\coinbase.py", line 37, in
 __init__
    self.add_output(out)
  File "C:\Users\ext\Desktop\pc\lib\TransactionManager\coinbase.py", line 58, in
 add_output
    output.transaction = self.hash_transaction()
  File "C:\Users\ext\Desktop\pc\lib\TransactionManager\transaction.py", line 123
, in hash_transaction
    self.hash.update(self.pack())
  File "E:\py3\lib\site-packages\Crypto\Hash\SHA256.py", line 96, in update
    expect_byte_string(data)
  File "E:\py3\lib\site-packages\Crypto\Util\_raw_api.py", line 172, in expect_b
yte_string
    raise TypeError("Only byte strings can be passed to C code")
TypeError: Only byte strings can be passed to C code
```

**Comment by xran-deex** [comment]
That looks like a problem introduced by using the pycryptodome library. I pushed a fix for it. Pull the latest and try again. I'd also delete the *.db and *.dat files before running again.

**Comment by CashCode** [comment]
pycryptodome is up to date. Same error.

**Comment by CashCode** [comment]
Same on linux

**Comment by CashCode** [comment]
Close pls. pycrypto and crypto are different libraries )
